[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://pumpfunds-production.up.railway.app/api"
  VITE_SOLANA_RPC_URL = "https://api.devnet.solana.com"
  VITE_NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000 